# Generated by Django 4.1 on 2025-01-05 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity", options={"verbose_name_plural": "Amenities"},
        ),
    ]
